<?php

namespace Drupal\gaz_migrate\Plugin\migrate\source;

use Drupal\migrate\Plugin\migrate\source\SqlBase;
use Drupal\migrate\Row;

/**
 * Provides a 'GazMigrateUsers' migrate source.
 *
 * @MigrateSource(
 *  id = "gaz_migrate_users"
 * )
 */
class GazMigrateUsers extends SqlBase {

  /**
   * {@inheritdoc}
   */
  public function query() {
    $query = $this->select('modx_users', 'u');
    $query->leftJoin('modx_user_attributes', 'a', 'u.id = a.id');
    $query->fields('u');
    $query->fields('a', ['email', 'lastlogin']);
    return $query;
  }

  /**
   * {@inheritdoc}
   */
  public function fields() {
    $fields = [
      'id' => $this->t('ID'),
      'username' => $this->t('username'),
      'active' => $this->t('Is user is active'),
      'primary_group' => $this->t('User group'),
      'email' => $this->t('User\'s email'),
      'sudo' => $this->t('Is admin or no'),
      'lastlogin' => $this->t('Last login'),
      'password' => $this->t('Password'),
      'salt' => $this->t('Salt'),
    ];
    return $fields;
  }

  /**
   * {@inheritdoc}
   */
  public function getIds() {
    return [
      'id' => [
        'type' => 'integer',
        'alias' => 'u'
      ],
    ];
  }

  function prepareRow(Row $row) {
    return parent::prepareRow($row); // TODO: Change the autogenerated stub
  }
}
